name: 'React Bundle Size'
description: 'Create a report of your bundle size'
author: 'Liam Read'
inputs:
  path:
    required: false
    description: 'The path to your react build folder'
    default: './build'
runs:
  using: 'node12'
  main: 'dist/index.js'
